-- 쿠팡 발주/공급 데이터를 저장하기 위한 테이블 생성
CREATE TABLE IF NOT EXISTS coupang_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    barcode TEXT NOT NULL,
    order_qty INTEGER DEFAULT 0,
    confirmed_qty INTEGER DEFAULT 0,
    received_qty INTEGER DEFAULT 0,
    unit_cost NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_coupang_orders_date ON coupang_orders(order_date);
CREATE INDEX IF NOT EXISTS idx_coupang_orders_barcode ON coupang_orders(barcode);

-- 기존 products 테이블과 조인을 위해 barcode는 products 테이블에 존재해야 함을 보장 (옵션)
-- ALTER TABLE coupang_orders ADD CONSTRAINT fk_coupang_orders_barcode FOREIGN KEY (barcode) REFERENCES products(barcode);
